import type { ExperienceConfig } from '../../types'
import { createExperienceRuntime } from '../experienceRuntime'
import { assetUrl } from '../../utils/assets'

const asset = (name: string) => assetUrl(`experiences/dahaus/${name}`)
const photo = (name: string) => asset(`reference/${name}`)

export const dahaus: ExperienceConfig = {
  id: 'dahaus',
  slug: 'dahaus',
  name: 'Dahaus!',
  experienceName: 'Noches Dahaus',
  tagline: 'Una noche. Una señal.',
  secondaryPhrase: 'La productora cambia de sede. La noche queda.',
  closingPhrase: 'No coleccionás lugares. Coleccionás noches.',
  logo: asset('wordmark.svg'),
  heroImage: photo('hero-ezequiel-crowd.jpg'),
  cameraImage: photo('hero-ezequiel-crowd.jpg'),
  eventImage: photo('picnic-dahaus-banner.png'),
  eventDate: 'PRÓXIMA EDICIÓN',
  location: 'Córdoba · sede itinerante',
  upcomingEvents: [
    { name: 'Cuartero x Dahaus!', date: '26.09 · Palacio Alsina Outdoor', image: photo('guy-j-dahaus-forja.png') },
    { name: 'Nick Varon / Fruta x Dahaus!', date: '03.10 · Palacio Alsina', image: photo('picnic-dahaus-banner.png') },
    { name: 'Ezequiel Arias & Simon Vuarambon', date: '14.11 · Forja Centro de Eventos', image: photo('ezequiel-arias-dahaus.jpg') },
  ],
  passportHistory: [
    { stationId: 'pulso', name: 'El Pulso', date: 'MOMENTO 01', image: photo('ostil-dahaus-palacio.png') },
    { stationId: 'cabina', name: 'La Cabina', date: 'MOMENTO 02', image: photo('sebastien-leger-dahaus.png') },
    { stationId: 'senal', name: 'La Señal', date: 'MOMENTO 03', image: photo('khen-dahaus-palacio.png') },
    { stationId: 'cierre', name: 'El Cierre', date: 'MOMENTO 04', image: photo('guy-j-dahaus-forja.png') },
    { stationId: 'la-fecha', name: 'La Fecha', date: 'EDICIÓN', image: photo('picnic-dahaus-banner.png') },
    { stationId: 'after', name: 'El Después', date: '', image: photo('ezequiel-arias-dahaus.jpg') },
  ],
  passportTotals: { nights: 1, stations: 4, specials: 1 },
  discovery: {
    allowDemoTapUnlock: true,
    demoTapStationIds: ['pulso', 'cabina', 'senal', 'cierre', 'la-fecha'],
  },
  theme: {
    background: '#080808',
    screen: '#111111',
    foreground: '#f5f3ee',
    accent: '#ef3d5b',
    border: 'rgba(245,243,238,.28)',
    borderSubtle: 'rgba(245,243,238,.14)',
    borderStrong: 'rgba(245,243,238,.46)',
    buttonBackground: '#f5f3ee',
    buttonForeground: '#090909',
    activeForeground: '#090909',
    cardRadius: '0px',
    contentPadding: '18px',
    stationCardHeight: '158px',
    homeCopyBottom: 'calc(69px + env(safe-area-inset-bottom, 0px) + 18px)',
    homeHeroPosition: 'center 42%',
    detailHeroHeight: '430px',
    navBackground: 'rgba(8,8,8,.92)',
  },
  content: {
    navigation: {
      explore: 'Explorar',
      camera: 'Escanear',
      passport: 'Pasaporte',
      upcoming: 'Próximas fechas',
      info: 'La experiencia',
      sponsors: 'Partners',
      reset: 'Reiniciar demo',
    },
    home: {
      tagLines: ['una señal', 'muchas sedes', 'frecuencia continua'],
      titleLines: ['Dahaus!'],
      demoLabel: 'Ciclo itinerante',
      startLabel: 'Entrar a la noche',
      demoNoteTitle: 'Demo conceptual.',
      demoNote: 'Las imágenes y el wordmark son referencias temporales con derechos pendientes.',
    },
    discover: {
      title: 'Encontrá la señal',
      descriptionLines: ['Apuntá al sello', 'en la entrada de la noche.'],
      logoLabel: 'Dahaus! · Demo',
      searchingLabel: 'Buscando',
      detectedLabel: 'Señal detectada',
      unlockingLabel: 'Abriendo acceso',
      completionHint: 'Cada señal habilita un momento del recorrido',
    },
    stations: {
      headerSuffix: 'Colección de noches',
      tabs: { all: 'Todas', permanent: 'Momentos', special: 'Edición' },
      permanentLabel: 'Momentos permanentes',
      eventLabel: 'La fecha',
      foundLabel: 'Encontrada',
      notFoundLabel: 'No encontrada',
      eventAvailability: 'Disponible durante esta edición.',
      secretFoundLabel: 'Señal secreta · Encontrada',
      secretLockedLabel: 'Señal secreta · No aparece en el plano.',
      tileTimesSingular: 'vez',
      tileTimesPlural: 'veces',
      explorationTitle: 'Recorrido Dahaus',
      explorationRemaining: 'Te falta una señal para completar la noche.',
      explorationComplete: 'Todavía queda una señal fuera del plano.',
    },
    detail: {
      page: '01 / 06',
      brandLabel: 'Dahaus!',
      subtitle: 'Una noche en movimiento',
      descriptionSuffix: 'Encontrala durante la edición.',
      usePhotoLabel: 'Usar este fondo',
    },
    unlocked: {
      brandLabel: 'Dahaus!',
      page: '05 / 06',
      unlockedLabel: '¡Señal desbloqueada!',
      specialEditionLabel: 'Edición especial',
      detailsLabel: 'Ver momento',
      photoLabel: 'Crear una foto',
    },
    secretReveal: {
      brandLabel: 'Dahaus!',
      page: '06 / 06',
      revealedLabel: 'Señal secreta revelada',
      subtitle: 'Fuera del plano',
      title: 'El Después',
      descriptionLines: ['Completaste el recorrido.', 'Ahora aparece el momento que la noche no anuncia.'],
      unlockLabel: 'Abrir momento',
    },
    passport: {
      eyebrow: 'No son sellos. Son noches.',
      title: 'Mi historial Dahaus',
      statLabels: { nights: 'noches', stations: 'momentos', specials: 'ediciones' },
      ticketLines: ['Dahaus!', 'Noches itinerantes'],
      secretLockedStatus: 'Señal secreta · Bloqueada',
      secretFoundStatus: 'Señal secreta · Encontrada',
      notFoundStatus: 'No encontrada',
      closingLines: ['La sede cambia.', 'La noche queda.'],
    },
    upcoming: {
      eyebrow: 'Nuevas fechas. Misma señal.',
      title: 'Próximas fechas',
      closingLines: ['Distintas sedes.', 'La misma noche.'],
    },
    photoStudio: {
      title: 'Tu noche Dahaus',
      subtitle: 'Elegí un momento de la noche.',
      lockedNotice: 'Desbloqueá La Fecha durante la edición.',
      newUnlockNotice: 'NUEVO FONDO DESBLOQUEADO · LA FECHA',
      controls: { photo: 'Foto', repeatPhoto: 'Repetir cámara', takePhoto: 'Tomar foto', publish: 'Compartir' },
      tabs: ['foto', 'story', 'post'],
      overlayLines: ['one night', 'many signals', 'dahaus!'],
    },
    sharing: {
      filenamePrefix: 'dahaus-noches-itinerantes',
      navigatorTitle: 'Dahaus! · Noches itinerantes',
      fallbackText: 'Una noche Dahaus.',
      imageAlt: 'Foto de Dahaus! · Noches itinerantes',
      instagramLines: ['Compartir', 'en Instagram'],
      downloadLines: ['Guardar', 'en tu galería'],
      otherNetworksLines: ['Otras redes'],
      editLabel: 'Volver a editar',
      creditLabel: 'Experiencia demo creada por CORSTENO',
    },
  },
  explorationStationIds: ['pulso', 'cabina', 'senal', 'cierre', 'la-fecha'],
  qrStationIds: ['pulso', 'cabina', 'senal', 'cierre', 'la-fecha'],
  photoStudio: {
    defaultFilterId: 'dahaus',
    segmentationBackgroundId: 'la-fecha',
    filters: [
      { id: 'dahaus', name: 'Dahaus!', image: photo('hero-ezequiel-crowd.jpg'), effect: 'contrast(1.08) saturate(.92)', background: photo('hero-ezequiel-crowd.jpg') },
      { id: 'pulso', name: 'EL PULSO', image: photo('ostil-dahaus-palacio.png'), effect: 'brightness(.88) contrast(1.12) saturate(1.08)', background: photo('ostil-dahaus-palacio.png') },
      { id: 'cabina', name: 'LA CABINA', image: photo('sebastien-leger-dahaus.png'), effect: 'brightness(.9) contrast(1.12) saturate(.82)', overlayColor: '#ef3d5b', background: photo('sebastien-leger-dahaus.png') },
      { id: 'senal', name: 'LA SEÑAL', image: photo('khen-dahaus-palacio.png'), effect: 'contrast(1.1) saturate(.96)', overlayColor: '#f5f3ee', background: photo('khen-dahaus-palacio.png') },
      { id: 'cierre', name: 'EL CIERRE', image: photo('guy-j-dahaus-forja.png'), effect: 'brightness(.84) contrast(1.16) saturate(.88)', overlayColor: '#ef3d5b', background: photo('guy-j-dahaus-forja.png') },
      { id: 'la-fecha', name: 'LA FECHA', image: photo('picnic-dahaus-banner.png'), effect: 'contrast(1.06) saturate(1.08)', overlayColor: '#f5f3ee', background: photo('picnic-dahaus-banner.png') },
      { id: 'after', name: 'EL DESPUÉS', image: photo('ezequiel-arias-dahaus.jpg'), effect: 'brightness(.76) contrast(1.18) saturate(.94)', overlayColor: '#ef3d5b', background: photo('ezequiel-arias-dahaus.jpg') },
    ],
  },
  stations: [
    { id: 'pulso', name: 'El Pulso', type: 'permanent', status: 'found', count: 1, description: 'La conexión inmediata entre la pista, el cuerpo y la señal que empieza a circular.', image: photo('ostil-dahaus-palacio.png'), location: 'Pista' },
    { id: 'cabina', name: 'La Cabina', type: 'permanent', status: 'found', count: 2, description: 'El punto de escucha donde una decisión cambia la temperatura de toda la noche.', image: photo('sebastien-leger-dahaus.png'), location: 'Cabina' },
    { id: 'senal', name: 'La Señal', type: 'permanent', status: 'found', count: 3, description: 'Gráfica, luz y sonido: una identidad que aparece aunque la sede cambie.', image: photo('khen-dahaus-palacio.png'), location: 'Visuales' },
    { id: 'cierre', name: 'El Cierre', type: 'permanent', status: 'found', count: 4, description: 'El último golpe, la pista todavía encendida y esa sensación de que falta una más.', image: photo('guy-j-dahaus-forja.png'), location: 'Último track' },
    { id: 'la-fecha', name: 'La Fecha', type: 'event', status: 'available', count: 0, description: 'La edición especial que reúne la señal, el público y una sede por descubrir.', image: photo('picnic-dahaus-banner.png'), location: 'Durante esta edición' },
    { id: 'after', name: 'El Después', type: 'secret', status: 'locked', count: 0, description: 'El momento fuera del plano. Aparece cuando la noche ya te reconoce.', image: photo('ezequiel-arias-dahaus.jpg') },
  ],
}

export const dahausRuntime = createExperienceRuntime(dahaus)
