import type { ExperienceConfig } from '../../types'
import { createExperienceRuntime } from '../experienceRuntime'
import { assetUrl } from '../../utils/assets'

const sunsetClaptoneImage = assetUrl('demo/sunset-claptone-crop.png')

export const laEstacion: ExperienceConfig = {
  id: 'la-estacion',
  slug: 'la-estacion',
  name: 'La Estación',
  experienceName: 'Tus Estaciones',
  tagline: 'Cada noche es distinta. Algunas no vuelven.',
  secondaryPhrase: 'No coleccionás premios. Coleccionás tus noches.',
  closingPhrase: 'Momentos que viviste. Lugares que descubriste. Noches que no vuelven.',
  logo: assetUrl('assets/la-estacion-logo.svg'),
  heroImage: assetUrl('demo/event-hero.png'),
  cameraImage: assetUrl('demo/camera-event.png'),
  eventImage: assetUrl('demo/lago-sunset.png'),
  eventDate: '09 · 09 · 26',
  location: 'Córdoba',
  upcomingEvents: [
    { name: 'La Estación Córdoba', date: '09 · 09 · 26', image: assetUrl('demo/event-hero.png') },
    { name: 'La Estación Buenos Aires', date: '21 · 11 · 26', image: assetUrl('demo/lago-sunset.png') },
    { name: 'La Estación Punta del Este', date: '15 · 01 · 27', image: assetUrl('demo/montana-sunset.png') },
  ],
  passportHistory: [
    { stationId: 'sunset-26', name: "Sunset '26", date: '09.09.26', image: sunsetClaptoneImage },
    { stationId: 'noche', name: 'Noche', date: '23.08.26', image: assetUrl('demo/noche-moon.png') },
    { stationId: 'fuego', name: 'Fuego', date: '12.07.26', image: assetUrl('demo/fuego-event.png') },
    { stationId: 'lago', name: 'Lago', date: '15.06.26', image: assetUrl('demo/lago-sunset.png') },
    { stationId: 'secret-01', name: 'AFTER HOURS', date: '', image: assetUrl('demo/camera-event.png') },
  ],
  passportTotals: { nights: 8, stations: 17, specials: 3 },
  storage: {
    legacyKey: 'corsteno-stations-demo',
    legacyExperienceId: 'la-estacion',
  },
  theme: {
    background: '#050708',
    screen: '#090d0f',
    foreground: '#f6f2eb',
    accent: '#e8c584',
    border: 'rgba(246,242,235,.23)',
    borderSubtle: 'rgba(246,242,235,.16)',
    borderStrong: 'rgba(246,242,235,.32)',
    buttonBackground: '#f6f2eb',
    buttonForeground: '#121617',
    activeForeground: '#171a19',
  },
  content: {
    navigation: {
      explore: 'Explorar',
      camera: 'Cámara',
      passport: 'Pasaporte',
      upcoming: 'Próximas fechas',
      info: 'Info',
      sponsors: 'Sponsors',
      reset: 'Reiniciar demo',
    },
    home: {
      tagLines: ['Más que', 'música', 'son momentos'],
      titleLines: ['Tus', 'Estaciones'],
      demoLabel: 'Demo',
      startLabel: 'Comenzar experiencia',
      demoNoteTitle: 'Demo interactiva.',
      demoNote: 'Esta experiencia es una demostración conceptual. Algunas funciones, contenidos y comportamientos pueden cambiar en una implementación final para evento.',
    },
    discover: {
      title: 'Buscá el lago',
      descriptionLines: ['Apuntá con tu cámara al logo', 'de la estación en el evento.'],
      logoLabel: 'La Estación',
      searchingLabel: 'Buscando',
      detectedLabel: 'Estación detectada',
      unlockingLabel: 'Desbloqueando',
      completionHint: 'Cuando lo encuentres se desbloquea una nueva estación',
    },
    stations: {
      headerSuffix: 'Tus estaciones -',
      tabs: { all: 'Todas', permanent: 'Permanentes', special: 'Especiales' },
      permanentLabel: 'Permanentes',
      eventLabel: 'Edición especial',
      foundLabel: 'Encontrada',
      notFoundLabel: 'No encontrada',
      eventAvailability: 'Disponible únicamente esta noche.',
      secretFoundLabel: 'Secret Station · Encontrada',
      secretLockedLabel: 'Secret Station · No todas las estaciones se anuncian.',
      tileTimesSingular: 'vez',
      tileTimesPlural: 'veces',
      explorationTitle: 'Exploración de esta noche',
      explorationRemaining: 'Te falta una estación.',
      explorationComplete: 'Hay algo más esperando.',
    },
    detail: {
      page: '05 / 06',
      brandLabel: 'La Estación',
      subtitle: 'El reflejo que nos une',
      descriptionSuffix: 'Encontrala en distintos puntos del evento.',
      usePhotoLabel: 'Usar en mis fotos',
    },
    unlocked: {
      brandLabel: 'La Estación',
      page: '04 / 04',
      unlockedLabel: '¡Desbloqueada!',
      specialEditionLabel: 'Edición especial',
      detailsLabel: 'Ver detalles',
      photoLabel: 'Crear una foto ahora',
    },
    secretReveal: {
      brandLabel: 'La Estación',
      page: '04 / 04',
      revealedLabel: 'Secret Station revelada',
      subtitle: 'La estación fuera del mapa',
      title: 'After Hours',
      descriptionLines: ['Estuviste en todas.', 'Ahora encontraste la que no estaba en el mapa.'],
      unlockLabel: 'Desbloquear',
    },
    passport: {
      eyebrow: 'No son eventos. Son recuerdos.',
      title: 'Mi pasaporte',
      statLabels: { nights: 'noches', stations: 'estaciones', specials: 'especiales' },
      ticketLines: ['La Estación', 'Tus Estaciones'],
      secretLockedStatus: 'Secret Station · Bloqueada',
      secretFoundStatus: 'Secret Station · Encontrada',
      notFoundStatus: 'No encontrada',
      closingLines: ['No coleccionás premios.', 'Coleccionás tus noches.'],
    },
    upcoming: {
      eyebrow: 'Nuevos lugares. Nuevas estaciones.',
      title: 'Próximas fechas',
      closingLines: ['Diferentes destinos.', 'La misma energía.'],
    },
    photoStudio: {
      title: 'Creá tu noche',
      subtitle: 'Usá los elementos de tus estaciones.',
      lockedNotice: "Encontrá SUNSET '26 durante el evento para desbloquearla.",
      newUnlockNotice: "NUEVO ELEMENTO DESBLOQUEADO · SUNSET '26",
      controls: { photo: 'Foto', repeatPhoto: 'Repetir foto', takePhoto: 'Tomar foto', publish: 'Post' },
      tabs: ['foto', 'story', 'post'],
      overlayLines: ['Same', 'people', 'different', 'skies +'],
    },
    sharing: {
      filenamePrefix: 'tus-estaciones',
      navigatorTitle: 'Tus Estaciones',
      fallbackText: 'Una noche de La Estación.',
      imageAlt: 'Foto de Tus Estaciones',
      instagramLines: ['Compartir', 'en Instagram'],
      downloadLines: ['Guardar', 'en tu galería'],
      otherNetworksLines: ['Otras redes'],
      editLabel: 'Repetir foto',
      creditLabel: 'Experiencia creada por CORSTENO',
    },
  },
  explorationStationIds: ['lago', 'fuego', 'noche', 'sunset-26'],
  qrStationIds: ['lago', 'fuego', 'noche', 'sunset-26'],
  photoStudio: {
    defaultFilterId: 'la-estacion',
    segmentationBackgroundId: 'lago',
    filters: [
      { id: 'la-estacion', name: 'La Estación', image: assetUrl('demo/event-hero.png'), effect: 'contrast(1.04) saturate(.92)', background: assetUrl('demo/event-hero.png') },
      { id: 'secret-01', name: 'AFTER HOURS', image: assetUrl('demo/camera-event.png'), effect: 'brightness(.78) contrast(1.12) saturate(.9) sepia(.12)', compositeEffect: 'brightness(.9) contrast(1.08) sepia(.08)', background: assetUrl('demo/camera-event.png') },
      { id: 'sunset-26', name: "Sunset '26", image: sunsetClaptoneImage, effect: 'saturate(1.12) contrast(1.03) sepia(.14)', background: assetUrl('demo/sunset-claptone-vertical.png') },
      { id: 'lago', name: 'Lago', image: assetUrl('demo/lago-sunset.png'), effect: 'saturate(.82) contrast(1.02) hue-rotate(8deg)', overlayColor: '#e8c584', background: assetUrl('demo/lago-sunset.png') },
      { id: 'fuego', name: 'Fuego', image: assetUrl('demo/fuego-event.png'), effect: 'saturate(1.16) contrast(1.06) sepia(.2)', overlayColor: '#f7c071', background: assetUrl('demo/fuego-event.png') },
      { id: 'noche', name: 'Noche', image: assetUrl('demo/noche-moon.png'), effect: 'brightness(.72) contrast(1.12) saturate(.78) hue-rotate(185deg)', mediaEffect: 'brightness(.86) contrast(1.12) saturate(.78) hue-rotate(185deg)', compositeEffect: 'brightness(1.12)', background: assetUrl('demo/noche-moon.png') },
    ],
  },
  stations: [
    { id: 'lago', name: 'Lago', type: 'permanent', status: 'found', count: 3, description: 'El agua, la calma y la energía de un lugar único.', image: assetUrl('demo/lago-sunset.png'), location: 'Hall oeste' },
    { id: 'montana', name: 'Montaña', type: 'permanent', status: 'found', count: 2, description: 'Una presencia que aparece sobre el ruido.', image: assetUrl('demo/montana-sunset.png'), location: 'Andén 03' },
    { id: 'fuego', name: 'Fuego', type: 'permanent', status: 'found', count: 4, description: 'Un pulso tibio debajo de la pista.', image: assetUrl('demo/fuego-event.png'), location: 'Túnel sur' },
    { id: 'noche', name: 'Noche', type: 'permanent', status: 'found', count: 1, description: 'La pieza que aparece cuando todo se apaga.', image: assetUrl('demo/noche-moon.png'), location: 'Nivel bajo' },
    { id: 'sunset-26', name: "Sunset '26", type: 'event', status: 'available', count: 0, description: 'Esta estación existe únicamente esta noche.', image: sunsetClaptoneImage, location: 'Hasta el cierre' },
    { id: 'secret-01', name: 'AFTER HOURS', type: 'secret', status: 'locked', count: 0, description: 'La estación que no estaba en el mapa.', image: assetUrl('demo/camera-event.png') },
  ],
}

export const laEstacionRuntime = createExperienceRuntime(laEstacion)
