import type { ExperienceConfig } from '../../types'
import { createExperienceRuntime } from '../experienceRuntime'
import { assetUrl } from '../../utils/assets'

const asset = (name: string) => assetUrl(`experiences/la-fabrica/${name}`)
const photo = (name: string) => asset(`reference/${name}`)

export const laFabrica: ExperienceConfig = {
  id: 'la-fabrica',
  slug: 'la-fabrica',
  name: 'La Fábrica',
  experienceName: 'El Gigante de Cemento',
  tagline: 'Una noche open air entre cemento y cielo.',
  secondaryPhrase: 'La pista cambia. La estructura queda.',
  closingPhrase: 'Cuatro zonas. Un gigante. Una noche que no vuelve.',
  logo: asset('wordmark.svg'),
  heroImage: photo('official-hero.webp'),
  cameraImage: photo('official-hero.webp'),
  eventImage: photo('official-hero.webp'),
  eventDate: 'EDICIÓN · OPEN AIR',
  location: 'Córdoba · El Gigante de Cemento',
  upcomingEvents: [
    { name: 'Open Air / próxima edición', date: 'LINE-UP A CONFIRMAR', image: photo('paradoks-open-air-2024.png') },
    { name: 'El Gigante / noche completa', date: 'FECHA A CONFIRMAR', image: photo('official-hero.webp') },
    { name: 'After / acceso por anuncio', date: 'SEÑAL RESERVADA', image: photo('darin-epsilon-booth-2018.jpg') },
  ],
  passportHistory: [
    { stationId: 'el-gigante', name: 'El Gigante', date: 'OPEN AIR', image: photo('official-hero.webp') },
    { stationId: 'cabina', name: 'Cabina', date: '04 / 04', image: photo('darin-epsilon-booth-2018.jpg') },
    { stationId: 'escenario', name: 'Escenario', date: '03 / 04', image: photo('camelphat-2023.jpg') },
    { stationId: 'open-air', name: 'Open Air', date: '02 / 04', image: photo('paradoks-open-air-2024.png') },
    { stationId: 'silos', name: 'Silos', date: '01 / 04', image: photo('richie-hawtin-2018.jpg') },
    { stationId: 'la-cantera', name: 'La Cantera', date: '', image: photo('hot-since-82-2023.jpg') },
  ],
  passportTotals: { nights: 1, stations: 4, specials: 1 },
  discovery: {
    allowDemoTapUnlock: true,
    demoTapStationIds: ['silos', 'open-air', 'escenario', 'cabina', 'el-gigante'],
  },
  theme: {
    background: '#070706',
    screen: '#0d0d0c',
    foreground: '#f4f0e9',
    accent: '#ee5b35',
    border: 'rgba(244,240,233,.25)',
    borderSubtle: 'rgba(244,240,233,.14)',
    borderStrong: 'rgba(244,240,233,.38)',
    buttonBackground: '#f4f0e9',
    buttonForeground: '#171412',
    activeForeground: '#1b0d09',
    cardRadius: '2px',
    contentPadding: '18px',
    stationCardHeight: '158px',
    homeCopyBottom: 'calc(69px + env(safe-area-inset-bottom, 0px) + 18px)',
    homeHeroPosition: 'center 38%',
    detailHeroHeight: '430px',
    navBackground: 'rgba(7,7,6,.9)',
  },
  content: {
    navigation: {
      explore: 'Explorar',
      camera: 'Escanear',
      passport: 'Pasaporte',
      upcoming: 'Próximas fechas',
      info: 'La experiencia',
      sponsors: 'Partners',
      reset: 'Reiniciar demo',
    },
    home: {
      tagLines: ['cemento', 'cielo abierto', 'frecuencia alta'],
      titleLines: ['La', 'Fábrica'],
      demoLabel: 'Experiencia demo',
      startLabel: 'Entrar al Gigante',
      demoNoteTitle: 'Propuesta comercial.',
      demoNote: 'La nomenclatura de zonas y el logo final quedan sujetos a validación con el venue.',
    },
    discover: {
      title: 'Encontrá la señal',
      descriptionLines: ['Apuntá al sello', 'en el acceso al Gigante.'],
      logoLabel: 'La Fábrica · Demo',
      searchingLabel: 'Buscando',
      detectedLabel: 'Señal detectada',
      unlockingLabel: 'Abriendo acceso',
      completionHint: 'Cada sello habilita una zona del recorrido',
    },
    stations: {
      headerSuffix: 'El Gigante de Cemento',
      tabs: { all: 'Todas', permanent: 'Zonas', special: 'Edición' },
      permanentLabel: 'Zonas permanentes',
      eventLabel: 'Edición especial',
      foundLabel: 'Encontrada',
      notFoundLabel: 'No encontrada',
      eventAvailability: 'Disponible durante esta edición.',
      secretFoundLabel: 'Señal secreta · Encontrada',
      secretLockedLabel: 'Señal secreta · No aparece en el plano.',
      tileTimesSingular: 'vez',
      tileTimesPlural: 'veces',
      explorationTitle: 'Recorrido del Gigante',
      explorationRemaining: 'Te falta una zona para completar el recorrido.',
      explorationComplete: 'Todavía queda una señal fuera del plano.',
    },
    detail: {
      page: '01 / 06',
      brandLabel: 'La Fábrica',
      subtitle: 'El pulso del Gigante',
      descriptionSuffix: 'Encontrala durante la edición.',
      usePhotoLabel: 'Usar este fondo',
    },
    unlocked: {
      brandLabel: 'La Fábrica',
      page: '05 / 06',
      unlockedLabel: '¡Señal desbloqueada!',
      specialEditionLabel: 'Edición especial',
      detailsLabel: 'Ver zona',
      photoLabel: 'Crear una foto',
    },
    secretReveal: {
      brandLabel: 'La Fábrica',
      page: '06 / 06',
      revealedLabel: 'Señal secreta revelada',
      subtitle: 'Fuera del plano',
      title: 'La Cantera',
      descriptionLines: ['Completaste el recorrido.', 'Ahora aparece la zona que el Gigante no anuncia.'],
      unlockLabel: 'Abrir zona',
    },
    passport: {
      eyebrow: 'No son sellos. Son coordenadas.',
      title: 'Mi pasaporte del Gigante',
      statLabels: { nights: 'noches', stations: 'zonas', specials: 'ediciones' },
      ticketLines: ['La Fábrica', 'El Gigante de Cemento'],
      secretLockedStatus: 'Señal secreta · Bloqueada',
      secretFoundStatus: 'Señal secreta · Encontrada',
      notFoundStatus: 'No encontrada',
      closingLines: ['La estructura queda.', 'La noche cambia.'],
    },
    upcoming: {
      eyebrow: 'Nuevas fechas. Misma estructura.',
      title: 'Próximas fechas',
      closingLines: ['Distintos line-ups.', 'El mismo Gigante.'],
    },
    photoStudio: {
      title: 'Tu noche en el Gigante',
      subtitle: 'Elegí una zona de La Fábrica.',
      lockedNotice: 'Desbloqueá la edición especial durante el evento.',
      newUnlockNotice: 'NUEVO FONDO DESBLOQUEADO · EL GIGANTE',
      controls: { photo: 'Foto', repeatPhoto: 'Repetir cámara', takePhoto: 'Tomar foto', publish: 'Compartir' },
      tabs: ['foto', 'story', 'post'],
      overlayLines: ['open', 'air', 'after', 'dark +'],
    },
    sharing: {
      filenamePrefix: 'la-fabrica-el-gigante',
      navigatorTitle: 'La Fábrica · El Gigante',
      fallbackText: 'Una noche en El Gigante de Cemento.',
      imageAlt: 'Foto de La Fábrica · El Gigante',
      instagramLines: ['Compartir', 'en Instagram'],
      downloadLines: ['Guardar', 'en tu galería'],
      otherNetworksLines: ['Otras redes'],
      editLabel: 'Volver a editar',
      creditLabel: 'Experiencia demo creada por CORSTENO',
    },
  },
  explorationStationIds: ['silos', 'open-air', 'escenario', 'cabina', 'el-gigante'],
  qrStationIds: ['silos', 'open-air', 'escenario', 'cabina', 'el-gigante'],
  photoStudio: {
    defaultFilterId: 'la-fabrica',
    segmentationBackgroundId: 'open-air',
    filters: [
      { id: 'la-fabrica', name: 'La Fábrica', image: photo('doctaclub-industrial-2018.png'), effect: 'contrast(1.08) saturate(.88)', background: photo('doctaclub-industrial-2018.png') },
      { id: 'la-cantera', name: 'LA CANTERA', image: photo('hot-since-82-2023.jpg'), effect: 'brightness(.76) contrast(1.18) saturate(1.08)', compositeEffect: 'brightness(.94) contrast(1.08)', background: photo('hot-since-82-2023.jpg') },
      { id: 'el-gigante', name: 'EL GIGANTE', image: photo('official-hero.webp'), effect: 'contrast(1.04) saturate(1.04) sepia(.06)', background: photo('official-hero.webp') },
      { id: 'silos', name: 'SILOS', image: photo('richie-hawtin-2018.jpg'), effect: 'brightness(.94) contrast(1.12) saturate(.84)', overlayColor: '#ee5b35', background: photo('richie-hawtin-2018.jpg') },
      { id: 'open-air', name: 'OPEN AIR', image: photo('paradoks-open-air-2024.png'), effect: 'saturate(.78) contrast(1.08) hue-rotate(155deg)', overlayColor: '#d2c8bb', background: photo('paradoks-open-air-2024.png') },
      { id: 'escenario', name: 'ESCENARIO', image: photo('camelphat-2023.jpg'), effect: 'contrast(1.14) saturate(.9)', overlayColor: '#ee5b35', background: photo('camelphat-2023.jpg') },
      { id: 'cabina', name: 'CABINA', image: photo('darin-epsilon-booth-2018.jpg'), effect: 'brightness(.9) contrast(1.12) saturate(.78) hue-rotate(8deg)', overlayColor: '#f1e8da', background: photo('darin-epsilon-booth-2018.jpg') },
    ],
  },
  stations: [
    { id: 'silos', name: 'Silos', type: 'permanent', status: 'found', count: 1, description: 'La estructura de cemento que define el perfil del Gigante cuando cae la noche.', image: photo('richie-hawtin-2018.jpg'), location: 'Estructuras' },
    { id: 'open-air', name: 'Open Air', type: 'permanent', status: 'found', count: 2, description: 'Cielo abierto, pista encendida y el pulso de la multitud entre las estructuras.', image: photo('paradoks-open-air-2024.png'), location: 'Pista central' },
    { id: 'escenario', name: 'Escenario', type: 'permanent', status: 'found', count: 3, description: 'El frente de la noche: humo, láseres y el golpe de la próxima canción.', image: photo('camelphat-2023.jpg'), location: 'Frente de pista' },
    { id: 'cabina', name: 'Cabina', type: 'permanent', status: 'found', count: 4, description: 'La señal detrás de la pista, donde se decide cuándo cambia la frecuencia.', image: photo('darin-epsilon-booth-2018.jpg'), location: 'Booth' },
    { id: 'el-gigante', name: 'El Gigante', type: 'event', status: 'available', count: 0, description: 'La edición especial que convierte la planta en un solo open air.', image: photo('official-hero.webp'), location: 'Durante esta edición' },
    { id: 'la-cantera', name: 'La Cantera', type: 'secret', status: 'locked', count: 0, description: 'La zona fuera del plano. Se revela cuando el recorrido está completo.', image: photo('hot-since-82-2023.jpg') },
  ],
}

export const laFabricaRuntime = createExperienceRuntime(laFabrica)
