import type { ExperienceConfig } from '../../types'
import { createExperienceRuntime } from '../experienceRuntime'
import { assetUrl } from '../../utils/assets'
import { laFabrica } from './laFabrica'

const art = (name: string) => assetUrl(`experiences/noctra/art/${name}.webp`)
export const noctra: ExperienceConfig = {
  ...laFabrica,
  id: 'noctra',
  slug: 'noctra',
  name: 'NOCTRA',
  experienceName: 'NOCTRA — Interactive Festival Experience',
  tagline: 'Tu noche. Tus momentos. Tu colección.',
  secondaryPhrase: 'Escaneá. Descubrí. Compartí.',
  closingPhrase: 'Mendoza — 2026 · Demo conceptual',
  logo: assetUrl('experiences/noctra/noctra-wordmark.svg'),
  heroImage: art('hero'),
  cameraImage: art('main-stage'),
  eventImage: art('main-stage'),
  eventDate: '2026',
  location: 'Mendoza',
  upcomingEvents: [],
  passportHistory: [
    { stationId: 'entrance', name: 'First Pulse', date: 'ACCESO', image: art('entrance'), requiresUnlock: true },
    { stationId: 'main-stage', name: 'Main Stage · Feel the Sound', date: 'ESCENARIO', image: art('main-stage') },
    { stationId: 'hidden-frequency', name: 'Hidden Frequency', date: 'FRECUENCIA OCULTA', image: art('hidden-frequency') },
    { stationId: 'nova-drop', name: 'NOVA Drop', date: 'ACTIVACIÓN', image: art('nova-drop'), requiresUnlock: true },
    { stationId: 'final-drop', name: 'Final Drop · Backstage', date: 'ACCESO BACKSTAGE', image: art('final-drop'), requiresUnlock: true, requiredExplorationCount: 3 },
  ],
  passportTotals: { nights: 1, stations: 2, specials: 2 },
  discovery: {
    allowDemoTapUnlock: true,
    demoTapStationIds: ['entrance', 'main-stage', 'nova-drop'],
  },
  storage: undefined,
  theme: {
    background: '#09090b',
    screen: '#111114',
    foreground: '#f3eee7',
    accent: '#e66b50',
    border: 'rgba(243,238,231,.2)',
    borderSubtle: 'rgba(243,238,231,.13)',
    borderStrong: 'rgba(243,238,231,.3)',
    buttonBackground: '#f3eee7',
    buttonForeground: '#111114',
    activeForeground: '#09090b',
    cardRadius: '3px',
    contentPadding: '22px',
    stationCardHeight: '164px',
    homeCopyBottom: 'calc(84px + env(safe-area-inset-bottom, 0px))',
    homeHeroPosition: 'center 48%',
    detailHeroHeight: '500px',
    navBackground: 'rgba(9,9,11,.88)',
  },
  content: {
    navigation: {
      explore: 'Explorar',
      camera: 'Descubrir',
      passport: 'Passport',
      upcoming: 'Line-up',
      info: 'La experiencia',
      sponsors: 'NOVA Drop',
      reset: 'Reiniciar demo',
    },
    home: {
      tagLines: ['Mendoza', '2026', 'Una noche en movimiento'],
      titleLines: ['NOCTRA'],
      demoLabel: '',
      startLabel: 'Explorar experiencia',
      demoNoteTitle: 'Demo conceptual.',
      demoNote: '',
      demoDisclosureTitle: 'DEMO CONCEPTUAL',
      demoDisclosureBody: 'Esta experiencia muestra cómo una productora puede transformar un evento en un recorrido interactivo con estaciones, contenido desbloqueable, activaciones de marca, Photo Studio y recompensas.',
      demoDisclosureNote: 'NOCTRA, NOVA y todo el contenido, nombres, premios y marcas mostrados son ficticios y pueden adaptarse a cada evento.',
      secondaryStartLabel: 'Comenzar recorrido',
    },
    discover: {
      title: 'Encontrá la señal',
      descriptionLines: ['Apuntá al código de una estación', 'o tocá el centro para probar la demo.'],
      logoLabel: 'NOCTRA',
      searchingLabel: 'Buscando señal',
      detectedLabel: 'Señal detectada',
      unlockingLabel: 'Experiencia desbloqueada',
      completionHint: 'Cada estación revela un momento de la noche.',
    },
    stations: {
      headerSuffix: 'Tu recorrido · Mendoza 2026',
      tabs: { all: 'Recorrido', permanent: 'Momentos', special: 'Edición' },
      permanentLabel: 'El recorrido',
      eventLabel: 'Esta edición',
      foundLabel: 'Desbloqueada',
      notFoundLabel: 'Por descubrir',
      eventAvailability: 'Encontrala durante esta noche.',
      secretFoundLabel: 'Frecuencia descubierta',
      secretLockedLabel: 'No aparece en el mapa.',
      tileTimesSingular: 'momento',
      tileTimesPlural: 'momentos',
      explorationTitle: 'Estaciones principales',
      explorationRemaining: 'Seguí explorando: cada señal abre algo nuevo.',
      explorationComplete: 'El recorrido está completo. Tu Final Drop ya está disponible.',
      explorationIntro: 'Cada señal suma un momento a tu recorrido.',
    },
    detail: {
      page: 'NOCTRA · MOMENTO',
      brandLabel: 'NOCTRA',
      subtitle: 'Mendoza — 2026',
      descriptionSuffix: 'Un momento para llevarte de la noche.',
      usePhotoLabel: 'Abrir Photo Studio',
    },
    unlocked: {
      brandLabel: 'NOCTRA',
      page: 'MAIN STAGE',
      unlockedLabel: 'Señal detectada',
      specialEditionLabel: 'Feel the Sound',
      detailsLabel: 'Ver experiencia',
      photoLabel: 'Crear una foto',
    },
    secretReveal: {
      brandLabel: 'NOCTRA',
      page: 'FRECUENCIA OCULTA',
      revealedLabel: 'SECRET FOUND',
      subtitle: 'Una señal fuera del mapa',
      title: 'Hidden Frequency',
      descriptionLines: ['Descubriste una experiencia oculta.', 'La frecuencia ya es tuya.'],
      unlockLabel: 'Desbloquear señal',
    },
    passport: {
      eyebrow: 'Tu colección de la noche',
      title: 'Festival Pass',
      statLabels: { nights: 'noche', stations: 'señales', specials: 'drops' },
      ticketLines: ['NOCTRA', 'Mendoza · 2026'],
      secretLockedStatus: 'Oculta · Sin descubrir',
      secretFoundStatus: 'Descubierta',
      notFoundStatus: 'Pendiente',
      closingLines: ['La noche sigue.', 'Tu colección también.'],
    },
    upcoming: {
      eyebrow: 'Mendoza · 2026',
      title: 'Line-up',
      closingLines: ['AERA · NOX · VOID', 'Nombres ficticios para una noche conceptual.'],
    },
    photoStudio: {
      title: 'Tu noche en NOCTRA',
      subtitle: 'Elegí un frame para tu historia.',
      lockedNotice: 'Descubrí esta estación para desbloquear su frame.',
      newUnlockNotice: 'NUEVA ESTACIÓN DESBLOQUEADA',
      controls: { photo: 'Foto', repeatPhoto: 'Repetir cámara', takePhoto: 'Tomar foto', publish: 'Compartir' },
      tabs: ['foto', 'story', 'post'],
      overlayLines: ['Mendoza', '2026', 'NOCTRA'],
    },
    sharing: {
      filenamePrefix: 'noctra-mendoza-2026',
      navigatorTitle: 'NOCTRA · Mendoza 2026',
      fallbackText: 'Tu noche. Tus momentos. Tu colección.',
      imageAlt: 'Momento de NOCTRA en Mendoza',
      instagramLines: ['Compartir', 'tu momento'],
      downloadLines: ['Guardar', 'en tu galería'],
      otherNetworksLines: ['Otras redes'],
      editLabel: 'Volver a crear',
      creditLabel: 'NOCTRA · MENDOZA 2026',
    },
  },
  explorationStationIds: ['entrance', 'main-stage', 'nova-drop'],
  qrStationIds: ['entrance', 'main-stage', 'nova-drop'],
  photoStudio: {
    defaultFilterId: 'entrance',
    segmentationBackgroundId: 'main-stage',
    filters: [
      { id: 'entrance', name: 'NOCTRA', image: art('entrance'), effect: 'contrast(1.08) saturate(.88)', background: art('entrance'), overlayColor: '#f3eee7' },
      { id: 'main-stage', name: 'MAIN STAGE', image: art('main-stage'), effect: 'contrast(1.12) saturate(.9)', background: art('main-stage'), overlayColor: '#f3eee7' },
      { id: 'nova-drop', name: 'I WAS HERE', image: art('nova-drop'), effect: 'contrast(1.08) saturate(.86)', background: art('nova-drop'), overlayColor: '#f3eee7' },
    ],
  },
  stations: [
    { id: 'entrance', name: 'First Pulse', type: 'permanent', status: 'available', count: 1, description: 'El primer pulso de la noche. Ya estás adentro; tu recorrido acaba de empezar.', image: art('entrance'), location: 'Entrada principal' },
    { id: 'main-stage', name: 'Feel the Sound', type: 'event', status: 'available', count: 2, description: 'Luces, visuales y el movimiento de toda la pista en un solo momento.', image: art('main-stage'), location: 'Escenario principal' },
    { id: 'hidden-frequency', name: 'Hidden Frequency', type: 'secret', status: 'locked', count: 3, description: 'Descubriste una experiencia que no aparece en el mapa.', image: art('hidden-frequency'), location: 'Señal oculta' },
    { id: 'nova-drop', name: 'NOVA Drop', type: 'permanent', status: 'available', count: 3, description: 'Una activación exclusiva. Tocá para revelar tu drop NOVA.', image: art('nova-drop'), location: 'NOVA experience' },
  ],
}

export const noctraRuntime = createExperienceRuntime(noctra)
